Rr data test
Repped-In-Tech/pipeline pull request #8
Opened 2023-01-12 18:51 UTC by rochelle-rossman

Threw some dummy data into index.js, installed react-bootstrap and reworked the card component a little bit and defined props. Mapping over and passing techies to the card component successfully. @drteresavasquez @drteresavasquez is this bad practice? I wanted the button to show only if there is a value and for the link to open in a new tab
```{userObj.githubUrl !== undefined ? (
            <Link href={userObj.githubUrl} passHref>
              <a target="_blank" href={userObj.githubUrl} rel="noreferrer">
                <button type="button" className="btn btn-primary">
                  GitHub
                </button>
              </a>
            </Link>
          ) : (
            ''
          )}

2023-01-12 19:52 UTC, drteresavasquez commented
Let's just check to see if the value evaluates to falsey. So, `user.githubUrl ?` For the condition.

2023-01-12 19:56 UTC, drteresavasquez requested changes
Now that I look at the data, I can see that some have properties on them that aren't in others. The conditions should still evaluate properly. Just test them first.

2023-01-12 19:56 UTC, drteresavasquez commented on components/Card.js
> +          {userObj.linkedInUrl !== undefined ? (
Let's change all of these by removing the !== condition. If they evaluate to falsey, it will render the false condition.

2023-01-12 20:00 UTC, rochelle-rossman commented on components/Card.js
> +          {userObj.linkedInUrl !== undefined ? (
Okay! I'll change that, I was curious if you had any thoughts on using an anchor tag inside of a next/link to get the link to open in a new tab?

2023-01-12 20:14 UTC, drteresavasquez commented on components/Card.js
> +          {userObj.linkedInUrl !== undefined ? (
@rochelle-rossman can you not just add the `target="_blank"` to the `<Link />`? Since the Link renders an a tag? Have you tried that?

2023-01-12 20:16 UTC, drteresavasquez commented on pages/index.js
> +    imageUrl: 'http://dummyimage.com/176x100.png/cc0000/ffffff',
@rochelle-rossman also, we are getting build errors on these. I know they are place holders, but let's use https: so the build will run

2023-01-12 23:55 UTC, rochelle-rossman commented on components/Card.js
> +          {userObj.linkedInUrl !== undefined ? (
@drteresavasquez it doesn't work without the additional a tag ¯\_(ツ)_/¯

2023-01-13 00:01 UTC, drteresavasquez commented on components/Card.js
> +          {userObj.linkedInUrl !== undefined ? (
Did you remove the passHref as well? I'll take a look in the morning and pull down your branch.

2023-01-13 00:12 UTC, drteresavasquez commented on components/Card.js
> +          {userObj.linkedInUrl !== undefined ? (
It's not needed unless you're passing the bed functionality to the child element.

2023-01-20 18:20 UTC, closed without merging